### ISSUE TITLE
mobile, patterns/learn: search "search" font and spacing different from news-test. 	maybe classic theme styles overriding?	maybe header styles added to news theme instead of this repo? font looks like being overridden by learn theme b/c targets any `label` tag, probably update learn css to be more targeted

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#73] opened 2022-01-11 17:23 UTC

**Comment by ryelle** [comment] 2022-01-12 23:40
Duplicate of #74

**Closed as completed by ryelle** 2022-01-12 23:40 UTC
Labels: [Type] Bug
