### ISSUE TITLE
Table of Contents: make whole header clickable

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-mu-plugins#533] opened 2023-12-05 02:54 UTC
> Can we also make the whole box clickable, not just the chevron?

_Originally posted by @jasmussen in https://github.com/WordPress/wporg-developer/issues/407

**Comment by ryelle** [comment] 2024-01-10 21:42
Duplicate of #547

**Closed as not planned by ryelle** 2024-01-10 21:42 UTC
