### ISSUE TITLE
Global header search styling could be improved

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-mu-plugins#550] opened 2023-12-18 12:57 UTC
I just noticed a few minor issues with the search in the global header, so flagging here. 

On desktop, the search field probably should fill the container.

| Current | Proposed |
|-|-|
|<img width="498" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/cb18923a-a38a-4f87-8cee-15a9404c8900">|<img width="516" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/7044a1dd-eb17-4bad-b6f9-acfc51f826d6">|

On mobile, the should be some padding in the overlay, similar to the navigation menu overlay. 

| Search overlay | Navigation overlay |
|-|-|
|<img width="581" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/08c971a8-b4b9-45a3-acdf-0eb948b5feba">|<img width="583" alt="image" src="https://github.com/WordPress/wporg-mu-plugins/assets/4832319/83afa50d-b8ba-43e2-a716-b4668af0676f">|

**Comment by ryelle** [comment] 2024-01-10 18:06
Closing this as a duplicate of #555, which I'd migrated to this repo before seeing this one.

**Closed as not planned by ryelle** 2024-01-10 18:06 UTC
Labels: [Block] Header & Footer
