### ISSUE TITLE
Nav component: Filter

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-mu-plugins#419] opened 2023-08-14 15:14 UTC
As part of the nav components used across the site, I have been testing ideas for the filter flow and ended up with a version that feels pretty solid and flexible to be used in all subsites. Before describing its parts, here are two prototype recordings showing a common used case based on Showcase designs ([wporg-showcase-2022#130](https://github.com/WordPress/wporg-showcase-2022/issues/130))

### Desktop
https://github.com/WordPress/wporg-main-2022/assets/895819/dbdf629e-5de6-4dff-a992-8b3ca1408d09

### Mobile

https://github.com/WordPress/wporg-main-2022/assets/895819/7f07f047-0b30-416d-ab0e-960cb322e71a

## Description

The core approach of this idea is browsing and applying filters per filter type. Other ideas I handled relied on a toggle displaying all filters and a single action for submitting all criteria, but this design was preferred due to its cleanest and transparency by showing up the available filters.

For pages where applying filters take you to a search results page, like in Showcase, the content area adds a result and sort bar above it. Otherwise, both bars are visible in the page. This idea aims to simplify the amount of pages and ways of searching and browsing content, so I envision that its feasibility will be revisited per subsite.

All subcomponents are 40px height and can be found in the `Filters 6.1` section of the [Filter component file](https://www.figma.com/file/82KoxsTqEYlcCzHoJCKPlt/Filter-component?type=design&node-id=196-7522&mode=design&t=s07eokbmWD9HVaAQ-4). They will be mark as ready for dev once we reach agreement.

<img width="1678" alt="UI components of Filter componet with all their states" src="https://github.com/WordPress/wporg-main-2022/assets/895819/9be7343e-a4d2-4ffa-b624-e105cc8d0575">

**Comment by adamwoodnz** [comment] 2023-08-14 21:22
Looks good, I was initially concerned about the 'Clear' action being within the dropdown, but seeing it in practice I think it works. I've [reached out for a11y feedback](https://wordpress.slack.com/archives/C02RP4X03/p1692047992453349).

**Comment by joedolson** [comment] 2023-08-15 18:22
Based on the design and description, I think this can be OK. @alexstine expressed a concern that it sounded like you can only use one at a time, but I don't think that's the case at all; you can enable any number of filters, then apply them.

The labeling could be tricky. It might be good to also append the number of filters applied in the 'Apply' button, e.g. 'Apply (3)', to confirm the number of filters being applied. How are these dropdowns expected to work when there are a large number of choices? The demos include only 7 tags; but some filters could easily have dozens.

**Comment by ryelle** [comment] 2023-08-15 21:19
> it sounded like you can only use one at a time, but I don't think that's the case at all; you can enable any number of filters, then apply them.

I think in this design, you can select any number of items in a dropdown (like multiple post tags), but you need to apply them before you can move to another dropdown. So to select the "fashion" & "art" tags and "store" category, you would need to open Tags, select fashion, select art, hit apply. The page will navigate to the fashion + art tag archive. Now you can open the Category dropdown, select store, and hit apply, and it should combine the two.

> For pages where applying filters take you to a search results page, like in Showcase, the content area adds a result and sort bar above it. Otherwise, both bars are visible in the page.

I'm not sure I'm following this. Looking at the figma (ignoring mobile for a minute), I see two layouts — one all in one row: search, result count, dropdowns. The other is two rows, search & dropdowns, then result count & sort. It looks like the single row is used on home, and the two row version is used on all archive pages. Is that right?

**Comment by fcoveram** [comment] 2023-08-16 10:47
To @joedolson's points

> It might be good to also append the number of filters applied in the 'Apply' button, e.g. 'Apply (3)', to confirm the number of filters being applied.

Great suggestion. I will make the change

> How are these dropdowns expected to work when there are a large number of choices? The demos include only 7 tags; but some filters could easily have dozens.

The area should be scrollable. I wonder if we should set a fixed height for small or big amount of items to prevent popover's height changes when opening/closing filters.

To @ryelle 

> I see two layouts — one all in one row: search, result count, dropdowns. The other is two rows, search & dropdowns, then result count & sort. It looks like the single row is used on home, and the two row version is used on all archive pages. Is that right?

Correct. One layout is for landing pages before searching or filtering, and the other layout is for search results/archive pages.

Thanks for the comments

**Comment by fcoveram** [comment] 2023-08-16 10:54
Now while revisiting the flow. Does it make sense to include the number of filters in the "Clear" button @joedolson? Attaching a screenshot of the current design for clearing filters.

<img width="1494" alt="Two mockups of filter flow. On the left, a filter popover with one filter selected, 'Clear' button enabled, and 'Apply' button disabled. On the right, a filter popover without any filter and 'Apply' button enabled" src="https://github.com/WordPress/wporg-mu-plugins/assets/895819/a9de0665-f2d1-4d60-b227-53228a92a356">

**Comment by joedolson** [comment] 2023-08-16 18:37
I don't think so. What's important about the number is that it informs the user how many filter they're adding, so it's a confirmation that they're making the number of changes they think they are. But "Clear" just removes all filters, and it makes no difference how many are active; it always sets that to zero. I don't think a user needs to know how many filters they're removing; it wouldn't change their action.

**Comment by fcoveram** [comment] 2023-08-21 10:44
[Filter flow's designs](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2712-1603&mode=design&t=qsXkb2V4HAuRj2rS-4) updated with the suggestions shared above.

**Comment by joedolson** [comment] 2023-09-14 20:57
Some early comments on the staging implementation (https://wordpress.org/showcase-v2/archives/)

- The tags don't scroll into visibility when tabbed. Tab to Popular Tags, press Enter, then tab through results - you can tab past the visible elements.
- Page scrolls when a tag is selected. Caused by `position:absolute` on the chekbox. The position is set to absolute, but not positioned, so it's pretty removed from the location of the label. When focus is set to the checkbox, the viewport shifts.
- Number of items selected isn't added to the Apply button, as per conversation above.

**Comment by ryelle** [comment] 2023-09-20 22:00
I've implemented the design & accessibility updates, so I'm going to close this issue— continued feedback is welcome, of course! feel free to open new issues for anything else.

**Closed as completed by ryelle** 2023-09-20 22:00 UTC
Labels: [Block] New Block
