### ISSUE TITLE
global footer links are not localized

### ISSUE THREAD

**Issue by timse201** [WordPress/wporg-mu-plugins#667] opened 2024-11-15 18:39 UTC
The links on the global footer are not localized which results in bad user experience.

**Comment by ryelle** [comment] 2024-11-15 18:53
@timse201 Can you explain a bit more about what you're seeing, and what you expect? I checked https://de.wordpress.org/ and I see the text is translated, and the links point to Rosetta sites where applicable (for example, Plugins goes to https://de.wordpress.org/plugins/, Vorlagen to https://de.wordpress.org/patterns/, etc).

**Comment by timse201** [comment] 2024-11-15 19:02
Thanks for reply.
I see these links on https://learn.wordpress.org/?locale=de_DE

**Comment by ryelle** [comment] 2024-11-15 19:07
As I mentioned in #668, this has the same root cause, so I'm going to close this issue. The fix will be tracked in the other issue.

**Closed as not planned by ryelle** 2024-11-15 19:07 UTC
