### ISSUE TITLE
Global header: fixed position hides targets

### ISSUE THREAD

**Issue by joyously** [WordPress/wporg-mu-plugins#203] opened 2022-04-12 16:06 UTC
When I click on a link to a comment, the browser loads the page and then moves that target to the top. But the header is in a fixed position at the top, so it covers the target.
I think it needs `scroll-margin-top` to account for the header height.
This example is using Firefox:
![hidden-target](https://user-images.githubusercontent.com/7957680/163005350-f9ccdd39-df47-4634-924a-a789ae0f7334.gif)

**Comment by ryelle** [comment] 2022-08-01 21:11
This is a duplicate of #219 — closing this one even though it's older, since the other has some discussion.

**Closed as not planned by ryelle** 2022-08-01 21:11 UTC
