### ISSUE TITLE
In support page in responsive width around 890px the hamburger menu navbar has background color issue.

### ISSUE THREAD

**Issue by Smit2808** [WordPress/wporg-mu-plugins#196] opened 2022-04-01 07:06 UTC
when the hamburger menu starts displaying on a width less than 890px, the menu has different bg color on top. And it's looking bad. I am attaching an image for better understanding.
Steps:
1. Open https://make.wordpress.org/support/ in responsive view width less than 890px.
2. Then open the hamburger menu and you can clearly see the background color issue on top of the menu, its background color is different from the menu color.

Image:
<img width="1440" alt="Screenshot 2022-04-01 at 12 35 47 PM" src="https://user-images.githubusercontent.com/64188895/161212784-16dd27e8-ac1f-4cbf-bdf0-5f867a16e8a3.png">

**Comment by iandunn** [comment] 2022-04-01 21:22
Good catch. Looks like `wp-block-navigation__responsive-container-content` needs `padding-top: 0` or something similar.

**Comment by Smit2808** [comment] 2022-04-06 06:48
Hi @iandunn sir,

As per your suggestion, I have created this pull request: https://github.com/WordPress/wporg-mu-plugins/pull/198/commits/63508474de6d5eef0a83130e6ac1a2cc96c01243 . I removed the padding top from the menu.

so this will work. But what I suggest is to change the background color and keep the padding-top as it is. If we change the background color like menu then it will look good. The color issue will be gone and padding will also be there as it is. So please if you like this suggestion then tell me. I will make PR for this.

**Comment by iandunn** [comment] 2022-04-06 17:52
🤔 That's a good point, removing the background from `wp-block-navigation__container` also works, and we'll want some padding there to match [the mockup](https://www.figma.com/file/O9I8Jl7kaUMTX39LlRGbGO/News-Page?node-id=7413%3A31182) (which isn't totally up to date).

It looks like we didn't use to have that style, but it was added in #178 for browser support. @StevenDufresne , do you have any thoughts on removing it, or changing it to `var(--wp--preset--color--darker-grey)` ?


_( Note: This can be reproduced in the local News repo too, not just on the Make sites. )_

**Comment by StevenDufresne** [comment] 2022-04-07 00:14
> It looks like we didn't use to have that style, but it was added in #178 for browser support. @StevenDufresne , do you have any thoughts on removing it, or changing it to `var(--wp--preset--color--darker-grey)` ?

Ah, I see, definitely a regression. We need the background color because of inheritance problems in older browsers. We can probably just use a media query and turn on that background color for our desktop view.  Removing the padding brings the clickable logo and the plugin link closer together than we probably want.

**Comment by Smit2808** [comment] 2022-04-07 06:49
Hi @iandunn and @StevenDufresne, I have added the media query as you said, added the media query for desktop view so now var(--wp--preset--color--darker-grey) color will only apply for desktop view. This will solve the issue. 

Please review this PR link: https://github.com/WordPress/wporg-mu-plugins/pull/201 . 

And thank you very much for discussing this issue.

**Comment by iandunn** [comment] 2022-04-07 18:32
Thanks!

**Comment by Smit2808** [comment] 2022-04-12 05:28
Hi @iandunn and @StevenDufresne, I have created the PR https://github.com/WordPress/wporg-mu-plugins/pull/202 , having media inside element. Please review it and merge it.  

Thank you.

**Comment by ryelle** [comment] 2022-08-22 19:12
I think this bug was fixed with #202, so I'm closing the issue.

**Closed as completed by ryelle** 2022-08-22 19:12 UTC
Labels: [Block] Header & Footer
