### ISSUE TITLE
Blue border around the menu

### ISSUE THREAD

**Issue by SchneiderSam** [WordPress/wporg-mu-plugins#144] opened 2022-02-02 14:53 UTC
Safari, iPad and after clicking an menu item i get this, just a few seconds. Then it disappears:
<img width="1180" alt="777" src="https://user-images.githubusercontent.com/9355398/152177754-ec3ea4b7-1212-4b8e-b700-1da7f2f67e00.png">

**Comment by iandunn** [comment] 2022-02-11 15:58
reproduced 👍🏻 

1. visit make.w.org in safari. it doesn't happen on w.org/news-test
2. click on `get involved`, but don't release button. the border appears around entire menu block
3. move mouse out of the viewport and release. that prevents navigating to a new page, and the blue border should remain

**Comment by ryelle** [comment] 2022-02-11 22:46
FYI, this was fixed in gutenberg in 12.4 — https://github.com/WordPress/gutenberg/pull/37824 — so this is only an issue on sites that don't have gutenberg active (I thought we had an issue for network-activating gutenberg, but I can't find it atm).

**Comment by coreymckrill** [comment] 2022-02-12 00:25
https://github.com/WordPress/wporg-news-2021/issues/251 mentions activating Gutenberg, and it looks like it is already active on the News site, running 12.5.4

**Comment by coreymckrill** [comment] 2022-02-12 00:26
Oh, I see, it's not on some other sites. Should we put network-activation on the launch task list?

**Comment by dd32** [comment] 2022-02-14 03:25
Reactivated Gutenberg on:
 - Main network
 - Make network
 - Global network
 - Profiles

I was unable to reproduce using the steps above before I activated Gutenberg, so can't tell if that fixed it or not.

**Comment by ryelle** [comment] 2022-02-14 15:43
Confirming this fixes the issue 👍🏻

**Closed as completed by ryelle** 2022-02-14 15:43 UTC
Labels: [Type] Bug
