### ISSUE TITLE
Overflow menu drops below header in Safari

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-mu-plugins#194] opened 2022-03-31 19:03 UTC
Reported at https://meta.trac.wordpress.org/ticket/6231

> When we open any get involved method ( Like Core, Meta etc... ) in safari ( version 15.3) with 1440px and lower media query then menu is fall down. Please see screenshot for more information.
>
> https://meta.trac.wordpress.org/raw-attachment/ticket/6231/wordpress.png

w.org currently has Gutenberg `12.8.1` pinned because of #193, so it's not caused by the same issue.

**Comment by ryelle** [comment] 2022-08-22 19:15
Is this still an issue? I can't reproduce, but I've only tried in Safari 15.6.1

**Comment by StevenDufresne** [comment] 2022-09-13 04:11
I see this on the homepage using:  `Safari Version 15.6.1 (17613.3.9.1.16)`

<img width="1161" alt="Screen Shot 2022-09-13 at 1 06 14 PM" src="https://user-images.githubusercontent.com/1657336/189805657-d256f95f-ff0c-41c6-80c1-8eff38648d57.png">


It's not exactly the same issue, but it's the same browser and component.

I see it happening on:
- https://wordpress.org
- https://wordpress.org/showcase/
- https://wordpress.org/news/
- more

I don't see it happening on:
- https://wordpress.org/about/
- https://learn.wordpress.org
- https://wordpress.org/patterns/
- more

**Comment by iandunn** [comment] 2022-09-13 18:12
Was the overflow menu removed when we switched to putting more things in submenus? If not, we can probably remove it since it's no longer being used. That might fix this issue.

**Comment by ryelle** [comment] 2022-09-13 21:50
The overflow menu code is still there, it's just not triggered in the default state because the menu is small now. If you zoom text you can trigger it still, ex:

![Screen Shot 2022-09-13 at 14 18 26](https://user-images.githubusercontent.com/541093/190012146-e1b74bec-9840-4124-8385-50250a429fb9.png)

(obviously that does not look great by itself, but could be fixed as part of https://github.com/WordPress/wporg-mu-plugins/issues/248)

Tracked the issue back to this update — https://github.com/WordPress/wporg-mu-plugins/commit/53e9eeb4b3f3264d3b9577766919591224a62ced — it looks like the `button` has a margin which probably didn't matter when that button wasn't full-height, and some of the old themes have resets that remove it.

**Comment by ryelle** [comment] 2022-09-13 21:54
Fixed that issue in b9ec0bcff21d797bd0ecb43f2f125b39aa7dfa93.

I think that is a different issue than the original report here, but we haven't been able to reproduce the original issue, so I'm inclined to close this.

**Closed as completed** 2022-09-14 00:06 UTC
Labels: [Type] Bug, [Block] Header & Footer
