### ISSUE TITLE
Update favorite button sizing to match buttons.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-mu-plugins#652] opened 2024-09-19 03:47 UTC
I think [this update](https://github.com/WordPress/wporg-parent-2021/commit/72058fa861e21480a3c96497882e6ce42431eb7f) that changes button line-height, results in the favorite button no longer being the same height as a sibling button.

## Screenshot
**Plugin Directory**
<img width="248" alt="Screenshot 2024-09-19 at 12 43 56 PM" src="https://github.com/user-attachments/assets/74b515a0-5788-441a-a3d6-e95241bd5668">

**Comment by ryelle** [comment] 2024-09-19 18:31
This is a duplicate of https://github.com/WordPress/wporg-parent-2021/issues/157.

**Closed as not planned by ryelle** 2024-09-19 18:31 UTC
