### ISSUE TITLE
Move Showcase to top-level navigation on WordPress.org

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-mu-plugins#342] opened 2023-02-20 02:19 UTC
Let's move 'Showcase' to the top-level of the navigation to give more prominence to the sites and examples. It should appear after 'About' as in this screenshot:

<img width="903" alt="Screenshot 2023-02-20 at 9 19 36 AM" src="https://user-images.githubusercontent.com/7133400/219994784-a2706f1b-43cd-4aa1-81ef-c715f8037538.png">

**Comment by eidolonnight** [comment] 2023-03-02 15:56
The approach we took with the main navigation (detailed in https://github.com/WordPress/wporg-mu-plugins/issues/251#issuecomment-1228545353) organized top-level items based on the frequency of visits (Eg. “About” might be most used by new visitors, but “News” will be used repeatedly by visitors every day). Based on this thinking, Showcase seems to me to belong further up the stack, perhaps before About?

**Comment by bengreeley** [comment] 2023-03-06 17:27
That's an excellent suggestion. Let's explore an exact location once we're ready to put it in the navigation once the Showcase website has been refreshed again.

**Comment by ryelle** [comment] 2023-10-03 18:12
Duplicate of #316

**Comment by pkevan** [comment] 2023-11-21 16:04
Showcase is now in the header as per #316.

**Closed as completed by pkevan** 2023-11-21 16:04 UTC
Labels: [Status] On Hold, [Block] Header & Footer

**Comment by bengreeley** [comment] 2023-11-21 16:10
> Showcase is now in the header as per #316.

Hell yeah.
